export const project = {
  name: 'project',
  title: 'Project',
  type: 'document',
  fields: [
    { name: 'title',            title: 'Title',             type: 'localeString' },
    { name: 'slug',             title: 'Slug',              type: 'slug', options: { source: 'title.en' } },
    { name: 'shortDescription', title: 'Short Description', type: 'localeString' },
    { name: 'longDescription',  title: 'Long Description',  type: 'localeText' },
    { name: 'coverImage',       title: 'Cover Image',       type: 'image' },
    { name: 'gallery',          title: 'Gallery',           type: 'array', of: [{ type: 'image' }] },
    { name: 'techStack',        title: 'Tech Stack',        type: 'array', of: [{ type: 'string' }] },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: { list: ['web', 'mobile', 'api', 'other'] },
    },
    { name: 'liveUrl',   title: 'Live URL',    type: 'url' },
    { name: 'githubUrl', title: 'GitHub URL',  type: 'url' },
    { name: 'startDate', title: 'Start Date',  type: 'date' },
    { name: 'endDate',   title: 'End Date',    type: 'date' },
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      options: { list: ['completed', 'in-progress', 'archived'] },
    },
    { name: 'featured', title: 'Featured', type: 'boolean' },
  ],
}
